#!/bin/sh

echo 'lint start -------------'
npm run lint

STAGE_FILES=$(git diff --cached --name-only -- '*')
echo $STAGE_FILES

git add $STAGE_FILES

eslint_output=$(npx next lint)
# Check if there are any ESLint errors
if [ $? -ne 0 ]; then
  exit 1
fi

# If there are no ESLint errors, allow the commit to proceed
exit 0
